export * from "@/pages/dashboard/Beranda";
export * from "@/pages/dashboard/Profil";
export * from "@/pages/dashboard/Tabel";
export * from "@/pages/dashboard/Pesanan";
export * from "@/pages/dashboard/Portofolio";
export * from "@/pages/dashboard/Layanan";
export * from "@/pages/dashboard/Paket";
export * from "@/pages/dashboard/Testimoni";
export * from "@/pages/dashboard/Faq";
